version: '3.8'
services:
  local_db:
    build:
      context: ./docker
      dockerfile: local_db.Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .db.env
    environment:
      POSTGRES_DB: postgres
    volumes:
      - local_db:/var/lib/postgresql/data

volumes:
  local_db:
    external: true